### ISSUE TITLE
Use ModelSignal instea of plain Signal

### ISSUE THREAD

**Issue by orf** [kmmbvnr/django-fsm#158]
I'm running into some circular imports when using the signals provided. Django provides a `ModelSignal` (db.models.signals.ModelSignal) that lets you give a model path to the `sender` argument instead of a concrete model class, i.e:

`@receiver(post_save, sender='myapp.MyModel', ...)`

Is it possible to update the signals to use ModelSignal instead of a plain Signal?

**Comment by kmmbvnr** [comment]
Generally, it should not be a problem since django 1,7 the recommended place for the signals is inside `AppConfig.ready` a method where models could be locally imported.

It looks that ModelSignal is part of undocumented django https://docs.djangoproject.com/en/1.10/search/?q=ModelSignal

So I prefer not to add this to the django-fsm.
