### ISSUE TITLE
Check mixins support

### ISSUE THREAD

**Issue by kmmbvnr** [kmmbvnr/django-fsm#75]
Mixins with @transition decorator

**Comment by bradmontgomery** [comment]
Hi, Do you mean adding support for implementing transition methods as a Mixin?  For example:

```python
class WorkflowMixin:

    @transition(field=state, source="*", target='draft')
    def draft(self):
        pass

    @transition(field=state, source="draft", target='published')
    def publish(self):
        pass
```

Then on a Model, you could mix in as follows: 

```python
class BlogPost(WorkflowMixin, models.Model):
    title = models.CharField()
    content = models.TextField()
    state = FSMField(default="draft")
```

In a previous project (using python 2; I haven't checked this lately), I could get around this by doing:

```python
class WorkflowMixin:
    state = None
    # ....
```
However, this currently does not work (in python 3.4) because the transition decorator sets the field prior to runtime (leading to a "AttributeError: 'NoneType' object has no attribute 'change_state'" exception, [here](https://github.com/kmmbvnr/django-fsm/blob/2.2.0/django_fsm/__init__.py#L468)).

I'd love to use fsm with mixins, but right now this doesn't seem possible.
